name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu:22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fb-worker-crawler:1.1 .
          docker tag ${{ secrets.DOCKER_USERNAME }}/fb-worker-crawler:1.1 ${{ secrets.DOCKER_USERNAME }}/fb-worker-crawler:${{ github.sha }}
      
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fb-worker-crawler:1.1 .
          docker push ${{ secrets.DOCKER_USERNAME }}/fb-worker-crawler:${{ github.sha }}
    
